In [7]:
distance = np.zeros((4+1, 5+1), dtype=int)
distance[0,:] = np.arange(0,5+1)
distance[:,0] = np.arange(0,4+1)
print(distance)

[[0 1 2 3 4 5]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]]


In [1]:
import numpy as np

def edit_distance_matrix(word1, word2):
    # Initialize the distance matrix
    distance = np.zeros((len(word1) + 1, len(word2) + 1), dtype=int)
    distance[0, :] = np.arange(len(word2) + 1)
    distance[:, 0] = np.arange(len(word1) + 1)

    # Compute minimum edit distances
    for i in range(1, len(word1) + 1):
        for j in range(1, len(word2) + 1):
            # Diagonal value (substitution)
            if word1[i - 1] != word2[j - 1]:
                diagonal_value = distance[i - 1, j - 1] + 2
            else:
                diagonal_value = distance[i - 1, j - 1]

            # Horizontal and vertical values (insertion and deletion)
            horizontal_value = distance[i - 1, j] + 1  # Insertion cost
            vertical_value = distance[i, j - 1] + 1    # Deletion cost

            # Minimum cost assignment
            distance[i, j] = min(diagonal_value, horizontal_value, vertical_value)

    return distance

# Test with example strings
str1 = "execution"
str2 = "intention"
distance = edit_distance_matrix(str1, str2)
distance


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  3,  4,  5,  6,  7,  8],
       [ 2,  3,  4,  5,  4,  5,  6,  7,  8,  9],
       [ 3,  4,  5,  6,  5,  6,  7,  8,  9, 10],
       [ 4,  5,  6,  7,  6,  7,  8,  9, 10, 11],
       [ 5,  6,  7,  8,  7,  8,  9, 10, 11, 12],
       [ 6,  7,  8,  7,  8,  9,  8,  9, 10, 11],
       [ 7,  6,  7,  8,  9, 10,  9,  8,  9, 10],
       [ 8,  7,  8,  9, 10, 11, 10,  9,  8,  9],
       [ 9,  8,  7,  8,  9, 10, 11, 10,  9,  8]])

In [ ]:
import numpy as np

def edit_distance_matrix(word1, word2):
    # Initialize the distance and direction matrices
    distance = np.zeros((len(word1) + 1, len(word2) + 1, 2), dtype=int)
    distance[0, :, 0] = np.arange(len(word2) + 1)  # Initialize distances
    distance[:, 0, 0] = np.arange(len(word1) + 1)  # Initialize distances
    distance[0, :, 1] = 1  # Initialize directions
    distance[:, 0, 1] = 2  # Initialize directions

    # Compute minimum edit distances and directions
    for i in range(1, len(word1) + 1):
        for j in range(1, len(word2) + 1):
            # Diagonal value (substitution)
            if word1[i - 1] != word2[j - 1]:
                diagonal_value = distance[i - 1, j - 1, 0] + 2
            else:
                diagonal_value = distance[i - 1, j - 1, 0]  # No cost for match

            # Horizontal and vertical values (insertion and deletion)
            horizontal_value = distance[i - 1, j, 0] + 1  # Insertion cost
            vertical_value = distance[i, j - 1, 0] + 1    # Deletion cost

            # Minimum cost assignment
            if diagonal_value <= horizontal_value and diagonal_value <= vertical_value:
                distance[i, j, 0] = diagonal_value
                distance[i, j, 1] = 0  # Diagonal direction
            elif horizontal_value <= diagonal_value and horizontal_value <= vertical_value:
                distance[i, j, 0] = horizontal_value
                distance[i, j, 1] = 1  # Horizontal direction
            else:
                distance[i, j, 0] = vertical_value
                distance[i, j, 1] = 2  # Vertical direction

    return distance


def traverse(distance): 
    letter_order = []
    i = distance.shape[0]-1
    j = distance.shape[1]-1
    while j >= 0 and i >=0:
        while j >= 0 and i >=0:
            if distance[i, j, 1] == 0:
                letter_order.append(0)
                i -= 1
                j -= 1
            elif distance[i, j, 1] == 1:
                letter_order.append(1)
                j -= 1
            else:
                letter_order.append(2)
                i -= 1
    
    letter_order = letter_order[::-1]
    return letter_order[1:]
            
# Test with example strings
str1 = "execution"
str2 = "intention"
distance = edit_distance_matrix(str1, str2)
order = traverse(distance)
print(order)
# [2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0]

[2, 0, 0, 0, 1, 0, 0, 0, 0, 0]


In [70]:
str1 = "book"
str2 = "baiok"
distance = edit_distance_matrix(str1, str2)
order = traverse(distance)
print(order)

[1, 1, 2, 0, 0, 0]


In [55]:
def order(distance): 
    letter_order = []
    i = distance.shape[0]-1
    j = distance.shape[1]-1
    while j >= 0 and i >=0:
        while j >= 0 and i >=0:
            print(i,j)
            if distance[i, j, 1] == 0:
                letter_order.append(0)
                i -= 1
                j -= 1
            elif distance[i, j, 1] == 1:
                letter_order.append(1)
                j -= 1
            else:
                letter_order.append(2)
                i -= 1
                
    return letter_order
            
order(distance) 

9 9
8 8
7 7
6 6
5 5
4 4
4 3
3 2
2 1
1 0
0 0


[0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 2]

In [ ]:
order = []

str1 = "execution"
str2 = "intention"
for i in range(distance.shape[0]-1):
    for j in range(distance.shape[1]-1):

['n', 'n', 'n', 'n', 'n', '-', '-', 'n', 'n', '-', 'o', 'o', 'o', 'o', 'o', 'o', 'o', 'o', '-', '-', 'i', 'i', 'i', 'i', 'i', '-', 'i', '-', '-', '-', 't', 't', 't', 't', 't', 't', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'u', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'c', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'e', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '-', '-', '-', '-', '-', 'e', 'e', 'e', 'e']
['n', '-', '-', '-', 'n', 'e', 't', 'n', '-', 'n', 'o', '-', '-', 'n', 'e', 't', 'n', '-', 'n', 'o', 'i', '-', 'n', 'e', '-', 'n', 'i', 'n', 'o', 'i', 't', 'n', '-', 't', 'n', 'i', 'n', 'o', 'i', 't', 'n', '-', 't', 'n', 'i', 'n', 'o', 'i', 't', 'n', '-', 't', 'n', 'i', 'n', 'o', 'i', 't', 'n', 'e', 't', 'n', 'i', 'n', 'o', 'i', 't', 'n', '-', 't', 'n', 'i', 'n', 'o', 'i', 't', 'n', 'e', 't', 'n', 'i']


In [3]:
def min_edit_distance_with_representation(str1, str2):
    len1, len2 = len(str1), len(str2)
    
    # Initialize the matrix
    dp = [[0 for _ in range(len2 + 1)] for _ in range(len1 + 1)]

    # Fill the base cases
    for i in range(len1 + 1):
        dp[i][0] = i
    for j in range(len2 + 1):
        dp[0][j] = j

    # Fill the DP matrix
    for i in range(1, len1 + 1):
        for j in range(1, len2 + 1):
            if str1[i - 1] == str2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]
            else:
                dp[i][j] = min(dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]) + 1

    # Traceback to get edit operations and aligned representations
    i, j = len1, len2
    operations = []
    aligned_str1 = []
    aligned_str2 = []

    while i > 0 or j > 0:
        if i > 0 and j > 0 and str1[i - 1] == str2[j - 1]:
            aligned_str1.append(str1[i - 1])
            aligned_str2.append(str2[j - 1])
            i -= 1
            j -= 1
        elif i > 0 and j > 0 and dp[i][j] == dp[i - 1][j - 1] + 1:
            operations.append(f"Substitute '{str1[i - 1]}' with '{str2[j - 1]}'")
            aligned_str1.append(str1[i - 1])
            aligned_str2.append(str2[j - 1])
            i -= 1
            j -= 1
        elif i > 0 and dp[i][j] == dp[i - 1][j] + 1:
            operations.append(f"Delete '{str1[i - 1]}'")
            aligned_str1.append(str1[i - 1])
            aligned_str2.append('_')
            i -= 1
        elif j > 0 and dp[i][j] == dp[i][j - 1] + 1:
            operations.append(f"Insert '{str2[j - 1]}'")
            aligned_str1.append('_')
            aligned_str2.append(str2[j - 1])
            j -= 1

    # Reverse the lists to show alignment from start to end
    aligned_str1.reverse()
    aligned_str2.reverse()
    operations.reverse()

    return dp[len1][len2], operations, aligned_str1, aligned_str2



str1 = "intention"
str2 = "execution"
distance, operations, aligned_str1, aligned_str2 = min_edit_distance_with_representation(str1, str2)

print(f"Minimum Edit Distance: {distance}")
print("Edit Operations:")
for op in operations:
    print(op)

print("\nAligned Strings:")
print(",".join(aligned_str1))
print(",".join(aligned_str2))

Minimum Edit Distance: 5
Edit Operations:
Substitute 'i' with 'e'
Substitute 'n' with 'x'
Substitute 't' with 'e'
Substitute 'e' with 'c'
Substitute 'n' with 'u'

Aligned Strings:
i,n,t,e,n,t,i,o,n
e,x,e,c,u,t,i,o,n


In [ ]:
i = len()
while(i)
    for j in reversed(range(3,0,-1)):
        print(i,j)
        break

3 1
2 1
1 1
