In [4]:
import numpy as np

# Transition Probabilities (a_ij) - Table
transition_probs = {
    'START': {'NN': 0.5, 'VB': 0.25, 'JJ': 0.25, 'RB': 0},
    'NN': {'NN': 0.25, 'VB': 0.5, 'JJ': 0, 'RB': 0},
    'VB': {'NN': 0.25, 'VB': 0, 'JJ': 0.25, 'RB': 0.25},
    'JJ': {'NN': 0, 'VB': 0.75, 'JJ': 0.25, 'RB': 0},
    'RB': {'NN': 0.5, 'VB': 0.25, 'JJ': 0.25, 'RB': 0}
}

# Emission Probabilities (b_ik) - Table
emission_probs = {
    'NN': {'time': 0.1, 'flies': 0.01, 'fast': 0.01},
    'VB': {'time': 0.01, 'flies': 0.1, 'fast': 0.01},
    'JJ': {'time': 0, 'flies': 0, 'fast': 0.1},
    'RB': {'time': 0, 'flies': 0, 'fast': 0.1}
}

def viterbi(sentence, tags, transition_probs, emission_probs):
    N = len(tags)
    T = len(sentence)

    viterbi_table = np.zeros((N, T))
    backpointer = np.zeros((N, T), dtype=int)

    for i, tag in enumerate(tags):
        viterbi_table[i, 0] = transition_probs['START'][tag] * emission_probs[tag].get(sentence[0], 0)
        backpointer[i, 0] = 0

    for t in range(1, T):
        for i, tag in enumerate(tags):
            max_prob, best_prev_tag = max(
                [(viterbi_table[j, t-1] * transition_probs[tags[j]].get(tag, 0), j) for j in range(N)],
                key=lambda x: x[0]
            )
            if(i==2):
                print(f"Max Prob : {max_prob} Best Prev Tag : {best_prev_tag}")
            viterbi_table[i, t] = max_prob * emission_probs[tag].get(sentence[t], 0)
            backpointer[i, t] = best_prev_tag

    final_probs = [viterbi_table[i, T-1] for i in range(N)]
    best_final_tag = np.argmax(final_probs)

    best_path = [best_final_tag]
    for t in range(T-1, 0, -1):
        best_path.insert(0, backpointer[best_path[0], t])

    best_tag_sequence = [tags[i] for i in best_path]

    return best_tag_sequence, max(final_probs)

tags = ['NN', 'VB', 'JJ', 'RB']
sentence = ['time', 'flies', 'fast']
best_sequence, best_prob = viterbi(sentence, tags, transition_probs, emission_probs)

# Output the results
print("Most probable POS tag sequence:", best_sequence)
print("Probability of the sequence:", best_prob)


Max Prob : 0.000625 Best Prev Tag : 1
Max Prob : 0.0006250000000000001 Best Prev Tag : 1
Viterbi Table : [[5.00e-02 1.25e-04 6.25e-06]
 [2.50e-03 2.50e-03 6.25e-07]
 [0.00e+00 0.00e+00 6.25e-05]
 [0.00e+00 0.00e+00 6.25e-05]]
Backpointer Table : [[0 0 1]
 [0 0 0]
 [0 1 1]
 [0 1 1]]
Most probable POS tag sequence: ['NN', 'VB', 'JJ']
Probability of the sequence: 6.250000000000001e-05


In [2]:
transition_probs = {
    'START': {'NN': 0.5, 'VB': 0.25, 'JJ': 0.25, 'RB': 0},
    'NN': {'NN': 0.25, 'VB': 0.5, 'JJ': 0, 'RB': 0},
    'VB': {'NN': 0.25, 'VB': 0, 'JJ': 0.25, 'RB': 0.25},
    'JJ': {'NN': 0, 'VB': 0.75, 'JJ': 0.25, 'RB': 0},
    'RB': {'NN': 0.5, 'VB': 0.25, 'JJ': 0.25, 'RB': 0}
}

# Emission Probabilities (b_ik) - Table
emission_probs = {
    'NN': {'time': 0.1, 'flies': 0.01, 'fast': 0.01},
    'VB': {'time': 0.01, 'flies': 0.1, 'fast': 0.01},
    'JJ': {'time': 0, 'flies': 0, 'fast': 0.1},
    'RB': {'time': 0, 'flies': 0, 'fast': 0.1}
}